### ISSUE TITLE
Fix `hasPendingGeth()`

### ISSUE THREAD

**Issue by lsaether** [ethereum-alarm-clock/eac.js#14]
I was doing must of my development using Parity and Ropsten and only recently switched over to using Geth and Rinkeby. I don't -think- that the function `hasPendingGeth()` is working properly. At least it wasn't when attempting to claim. It probably just needs to be tweaked, the way that Geth's RPC request returns data is kinda annoying.

```
const hasPendingGeth = (conf, txRequest) => {
    /// Only available if using Geth locally.
    const Web3 = require('web3')
    const provider = new Web3.providers.HttpProvider(`${conf.provider}`)

    return new Promise((resolve, reject) => {
        provider.send({
            "jsonrpc": "2.0",
            "method": "txpool_content",
            "params": [],
            "id": 0o7
        }, (err, res) => {
            if (err) reject(err)
            for (let account in res.result.pending) {
                for (let nonce in res.result.pending[account]) {
                    if (res.result.pending[account][nonce].to === txRequest.address) {
                        resolve(true)
                    }
                }
            }
            resolve(false)
        })
    })
}
```

**Comment by kosecki123** [comment]
txpool API is exposed by default over IPC only. eac.js is using HTTP protocol. It's possible to enable txpool over HTTP with --httpapi switch of geth. I think updating instruction on how to a local node will do the job.
