### ISSUE TITLE
Text barely readable on white console

### ISSUE THREAD

**Issue by kosecki123** [ethereum-alarm-clock/eac.js#28]
Dark blue with black text, unable to read what's there

<img width="349" alt="screen shot 2018-01-25 at 12 10 49" src="https://user-images.githubusercontent.com/5417665/35385533-e87ef7e2-01c8-11e8-98dc-e5437e796750.png">

**Comment by lsaether** [comment]
I think what I'll do is take chalk out completely, so I don't have to worry about it being a dependency.

**Comment by lsaether** [comment]
Removed chalk in commit https://github.com/ethereum-alarm-clock/eac.js/commit/40ff24d7df6aac25d74ec601e29db5087f708a4a#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L29
