### ISSUE TITLE
Add some nicer detection if Web3 provider is not available

### ISSUE THREAD

**Issue by kosecki123** [ethereum-alarm-clock/eac.js#29]
Today we just failing with

`[FATAL] Error: Invalid JSON RPC response: undefined`

when trying to start `eac.js` and local node is not available

**Comment by lsaether** [comment]
Already had this for the client but brought it out for the scheduler too https://github.com/ethereum-alarm-clock/eac.js/commit/40ff24d7df6aac25d74ec601e29db5087f708a4a#diff-d3c49959215652ea0648588b82ff5e27R362
