### ISSUE TITLE
Add `--drainWallet` flag to empty wallet account of their ether

### ISSUE THREAD

**Issue by lsaether** [ethereum-alarm-clock/eac.js#5]
The `eac` command so far has two wallet flags implemented, `--createWallet` and `--fundWallet` to create a light wallet that will send execution calls and to send ether to these accounts. I anticipate the use case of someone wanting to exit the system and "withdraw" all the ether used in these children account. Or maybe they want to withdraw some of the earnings of their accounts while keeping enough funds in to continue execution. Right now users would have to empty each account manually or write a script of their own. We should add another option like the two above called `--drainWallet` or `--withdrawFromWallet <num>`  where `num` is an amount greater than zero but less than the total amount in the accounts. Drain wallet would send the entire balance of the accounts.

**Comment by lsaether** [comment]
It would need to target a specific address like so: `--drainWallet <target>` where target is a valid Ethereum address.

**Comment by kosecki123** [comment]
What is actually the benefit of having multiple accounts inside the wallet?

**Comment by lsaether** [comment]
The idea is that it allows for parallelization of transactions that do not depend on a single account's nonce. Since people can set the gas price to a variable of their choosing it's possible that they will choose a gas price that will be lower than the network's average. This would leave that transaction in a "pending state" for minutes or possibly longer. This account would no longer be able to send transactions since the new transactions would increment the nonce and the network will not process transactions with out of order nonces.

The multiple accounts are an attempt to provide resiliency and mitigate this scenario. Since it's quite likely it may happen to one account, the other accounts can continue to execute independently.

**Comment by lsaether** [comment]
e988bf11247118e35c07bdb50aa6e697075717f2 closes
